all: test

prepare:
	go get -u -v github.com/stretchr/testify/...
	go get -u -v github.com/axw/gocov/...

test:
	go install -v ./...
	gocov test -v github.com/AlekSi/gocov-xml/internal/package1 > package1.gocov.json
	gocov-xml < package1.gocov.json > package1.gocov.xml
	xmllint --valid --noout package1.gocov.xml
	go test ./...
